# Generated by Django 3.2.8 on 2022-02-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
