# Generated by Django 3.2.8 on 2021-11-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='responsibility',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
